default: &default
  adapter: ENV['DB']
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: hackinghealth_development

production:
  <<: *default
  database: hacknighealth_production

test:
  <<: *default
  database: hackinghealth_test

